-- Database: bibs

-- DROP DATABASE bibs;

CREATE DATABASE bibs
  WITH OWNER = postgres
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'Spanish_Argentina.1252'
       LC_CTYPE = 'Spanish_Argentina.1252'
       CONNECTION LIMIT = -1;


CREATE TABLE public.whoscored_match_report
(
idmatch integer NOT NULL,
country character varying(50) NOT NULL,
league character varying(50) NOT NULL,
temp character varying(50) NOT NULL,
equipol character varying(50) NOT NULL,
fecha date NOT NULL,
hora time NOT NULL,
equipov character varying(50) NOT NULL,
golesl	numeric(7,2) null,
golesv	numeric(7,2) null,
totalshotsl	numeric(7,2) null,
totalshotsv	numeric(7,2) null,
woodworkl	numeric(7,2) null,
woodworkv	numeric(7,2) null,
shotsontargetl	numeric(7,2) null,
shotsontargetv	numeric(7,2) null,
shotsofftargetl	numeric(7,2) null,
shotsofftargetv	numeric(7,2) null,
shotsblockedl	numeric(7,2) null,
shotsblockedv	numeric(7,2) null,
possessionl	numeric(7,2) null,
possessionv	numeric(7,2) null,
touchesl	numeric(7,2) null,
touchesv	numeric(7,2) null,
passsuccessl	numeric(7,2) null,
passsuccessv	numeric(7,2) null,
totalpassesl	numeric(7,2) null,
totalpassesv	numeric(7,2) null,
accuratepassesl	numeric(7,2) null,
accuratepassesv	numeric(7,2) null,
keypassesl	numeric(7,2) null,
keypassesv	numeric(7,2) null,
dribbleswonl	numeric(7,2) null,
dribbleswonv	numeric(7,2) null,
dribblesattemptedl	numeric(7,2) null,
dribblesattemptedv	numeric(7,2) null,
dribbledpastl	numeric(7,2) null,
dribbledpastv	numeric(7,2) null,
dribblesuccessl	numeric(7,2) null,
dribblesuccessv	numeric(7,2) null,
aerialswonl	numeric(7,2) null,
aerialswonv	numeric(7,2) null,
offensiveaerialsl	numeric(7,2) null,
offensiveaerialsv	numeric(7,2) null,
defensiveaerialsl	numeric(7,2) null,
defensiveaerialsv	numeric(7,2) null,
successfultacklesl	numeric(7,2) null,
successfultacklesv	numeric(7,2) null,
tacklesattemptedl	numeric(7,2) null,
tacklesattemptedv	numeric(7,2) null,
wasdribbledl	numeric(7,2) null,
wasdribbledv	numeric(7,2) null,
tacklesuccessl	numeric(7,2) null,
tacklesuccessv	numeric(7,2) null,
clearancesl	numeric(7,2) null,
clearancesv	numeric(7,2) null,
interceptionsl	numeric(7,2) null,
interceptionsv	numeric(7,2) null,
cornersl	numeric(7,2) null,
cornersv	numeric(7,2) null,
corneraccuracyl	numeric(7,2) null,
corneraccuracyv	numeric(7,2) null,
dispossessedl	numeric(7,2) null,
dispossessedv	numeric(7,2) null,
errorsl	numeric(7,2) null,
errorsv	numeric(7,2) null,
foulsl	numeric(7,2) null,
foulsv	numeric(7,2) null,
offsidesl	numeric(7,2) null,
offsidesv	numeric(7,2) null
)
WITH (
  OIDS=FALSE
);

ALTER TABLE public.whoscored_match_report
	ADD CONSTRAINT pk_whoscored_match_report PRIMARY KEY (idmatch,country,league,temp);

ALTER TABLE public.whoscored_match_report
  OWNER TO postgres;



-- Function: public.ins_json(boolean, character varying, integer, integer, integer)

-- DROP FUNCTION public.ins_json(boolean, character varying, integer, integer, integer);

CREATE OR REPLACE FUNCTION public.import_ws_reportmatches(
_idmatch integer ,
_country character varying ,
_league character varying ,
_temp character varying ,
_equipol character varying ,
_fecha date ,
_hora time ,
_equipov character varying ,
_golesl numeric,
_golesv numeric,
_totalshotsl	numeric ,
_totalshotsv	numeric ,
_woodworkl	numeric ,
_woodworkv	numeric ,
_shotsontargetl	numeric ,
_shotsontargetv	numeric ,
_shotsofftargetl	numeric ,
_shotsofftargetv	numeric ,
_shotsblockedl	numeric ,
_shotsblockedv	numeric ,
_possessionl	numeric ,
_possessionv	numeric ,
_touchesl	numeric ,
_touchesv	numeric ,
_passsuccessl	numeric ,
_passsuccessv	numeric ,
_totalpassesl	numeric ,
_totalpassesv	numeric ,
_accuratepassesl	numeric ,
_accuratepassesv	numeric ,
_keypassesl	numeric ,
_keypassesv	numeric ,
_dribbleswonl	numeric ,
_dribbleswonv	numeric ,
_dribblesattemptedl	numeric ,
_dribblesattemptedv	numeric ,
_dribbledpastl	numeric ,
_dribbledpastv	numeric ,
_dribblesuccessl	numeric ,
_dribblesuccessv	numeric ,
_aerialswonl	numeric ,
_aerialswonv	numeric ,
_offensiveaerialsl	numeric ,
_offensiveaerialsv	numeric ,
_defensiveaerialsl	numeric ,
_defensiveaerialsv	numeric ,
_successfultacklesl	numeric ,
_successfultacklesv	numeric ,
_tacklesattemptedl	numeric ,
_tacklesattemptedv	numeric ,
_wasdribbledl	numeric ,
_wasdribbledv	numeric ,
_tacklesuccessl	numeric ,
_tacklesuccessv	numeric ,
_clearancesl	numeric ,
_clearancesv	numeric ,
_interceptionsl	numeric ,
_interceptionsv	numeric ,
_cornersl	numeric ,
_cornersv	numeric ,
_corneraccuracyl	numeric ,
_corneraccuracyv	numeric ,
_dispossessedl	numeric ,
_dispossessedv	numeric ,
_errorsl	numeric ,
_errorsv	numeric ,
_foulsl	numeric ,
_foulsv	numeric ,
_offsidesl	numeric ,
_offsidesv	numeric )
  RETURNS void AS
$BODY$

INSERT INTO public.whoscored_match_report(
            idmatch  ,
country ,
league ,
temp ,
equipol ,
fecha ,
hora ,
equipov ,
golesl,
golesv,
totalshotsl	 ,
totalshotsv	 ,
woodworkl	 ,
woodworkv	 ,
shotsontargetl	 ,
shotsontargetv	 ,
shotsofftargetl	 ,
shotsofftargetv	 ,
shotsblockedl	 ,
shotsblockedv	 ,
possessionl	 ,
possessionv	 ,
touchesl	 ,
touchesv	 ,
passsuccessl	 ,
passsuccessv	 ,
totalpassesl	 ,
totalpassesv	 ,
accuratepassesl	 ,
accuratepassesv	 ,
keypassesl	 ,
keypassesv	 ,
dribbleswonl	 ,
dribbleswonv	 ,
dribblesattemptedl	 ,
dribblesattemptedv	 ,
dribbledpastl	 ,
dribbledpastv	 ,
dribblesuccessl	 ,
dribblesuccessv	 ,
aerialswonl	 ,
aerialswonv	 ,
offensiveaerialsl	 ,
offensiveaerialsv	 ,
defensiveaerialsl	 ,
defensiveaerialsv	 ,
successfultacklesl	 ,
successfultacklesv	 ,
tacklesattemptedl	 ,
tacklesattemptedv	 ,
wasdribbledl	 ,
wasdribbledv	 ,
tacklesuccessl	 ,
tacklesuccessv	 ,
clearancesl	 ,
clearancesv	 ,
interceptionsl	 ,
interceptionsv	 ,
cornersl	 ,
cornersv	 ,
corneraccuracyl	 ,
corneraccuracyv	 ,
dispossessedl	 ,
dispossessedv	 ,
errorsl	 ,
errorsv	 ,
foulsl	 ,
foulsv	 ,
offsidesl	 ,
offsidesv	
			)
    VALUES (_idmatch  ,
_country ,
_league ,
_temp ,
_equipol ,
_fecha ,
_hora ,
_equipov ,
_golesl,
_golesv,
_totalshotsl	 ,
_totalshotsv	 ,
_woodworkl	 ,
_woodworkv	 ,
_shotsontargetl	 ,
_shotsontargetv	 ,
_shotsofftargetl	 ,
_shotsofftargetv	 ,
_shotsblockedl	 ,
_shotsblockedv	 ,
_possessionl	 ,
_possessionv	 ,
_touchesl	 ,
_touchesv	 ,
_passsuccessl	 ,
_passsuccessv	 ,
_totalpassesl	 ,
_totalpassesv	 ,
_accuratepassesl	 ,
_accuratepassesv	 ,
_keypassesl	 ,
_keypassesv	 ,
_dribbleswonl	 ,
_dribbleswonv	 ,
_dribblesattemptedl	 ,
_dribblesattemptedv	 ,
_dribbledpastl	 ,
_dribbledpastv	 ,
_dribblesuccessl	 ,
_dribblesuccessv	 ,
_aerialswonl	 ,
_aerialswonv	 ,
_offensiveaerialsl	 ,
_offensiveaerialsv	 ,
_defensiveaerialsl	 ,
_defensiveaerialsv	 ,
_successfultacklesl	 ,
_successfultacklesv	 ,
_tacklesattemptedl	 ,
_tacklesattemptedv	 ,
_wasdribbledl	 ,
_wasdribbledv	 ,
_tacklesuccessl	 ,
_tacklesuccessv	 ,
_clearancesl	 ,
_clearancesv	 ,
_interceptionsl	 ,
_interceptionsv	 ,
_cornersl	 ,
_cornersv	 ,
_corneraccuracyl	 ,
_corneraccuracyv	 ,
_dispossessedl	 ,
_dispossessedv	 ,
_errorsl	 ,
_errorsv	 ,
_foulsl	 ,
_foulsv	 ,
_offsidesl	 ,
_offsidesv);

$BODY$
  LANGUAGE sql ;
--ALTER FUNCTION public.whoscored_match_report(boolean, character varying, integer, integer, integer)
--  OWNER TO postgres;

